apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: mattermost
spec:
  size: 100users                               # Adjust to your requirements
  ingressName: mattermost.smartforce.es.airbusds.corp  # Adjust to your domain
  # ingressAnnotations:
  #   kubernetes.io/ingress.class: nginx
  version: 5.31.0
  licenseSecret: ""                            # If you have created secret in guide step 1, put its name here