---
- hosts: all
  remote_user: "{{ user  }}"
  become: yes
  vars_files:
    - "../vars/docker.yml"
    - "../vars/k8s.yml"
    - "../vars/host-config.yml"
  tasks:
    - name: Configure all machines
      include: ../tasks/configure-hosts.yml

    - name: Provision and benchmark Docker and Kubernetes
      include: ../tasks/main.yml

    - name: Clear packages on all machines
      include: ../tasks/autoremove.yml